# Render configuration for Task Tracker Pro (Free Tier)
version: "1"

services:
  # Main web application
  - type: web
    name: task-tracker-pro
    runtime: python
    plan: free
    region: oregon  # Choose the region closest to your users
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py makemigrations tracker
      python manage.py migrate
      python manage.py createsuperuser --noinput || true
    startCommand: gunicorn task_tracker_pro.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      # Core environment variables
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"  # Allows all Render subdomains
      - key: RENDER
        value: "True"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"  # Allows all Render subdomains
      
      # Database connection
      - key: DATABASE_URL
        fromDatabase:
          name: task-tracker-db
          property: connectionString
      
      # Superuser creation (set these in the Render dashboard)
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      
      # AI configuration (using local fallback for free tier)
      - key: OLLAMA_BASE_URL
        value: "http://localhost:11434"  # Default to local Ollama instance
      - key: OLLAMA_MODEL
        value: "mistral"
      - key: WHISPER_ENABLED
        value: "False"

# Database definition
databases:
  - name: task-tracker-db
    plan: free
    region: oregon  # Same region as the web service
    databaseName: task_tracker
    user: task_tracker_user
