# Render configuration for Task Tracker Pro
# Updated version based on exported configuration
version: "1"

services:
  # Main web application
  - type: web
    name: task_tracker_pro  # Using underscores to match existing deployment
    runtime: python
    repo: https://github.com/ngoyal78/task_tracker_pro  # Your GitHub repository
    plan: free
    region: oregon  # Matching existing deployment region
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      python manage.py createsuperuser --noinput || true  # Create superuser if env vars are set
    startCommand: gunicorn task_tracker_pro.wsgi:application --bind 0.0.0.0:8000
    autoDeploy: true
    envVars:
      # Core environment variables
      - key: SECRET_KEY
        sync: false  # Set this manually in the Render dashboard
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false  # Set this manually in the Render dashboard
      - key: RENDER
        value: "True"
      - key: CSRF_TRUSTED_ORIGINS
        sync: false  # Set this manually in the Render dashboard
      
      # Database connection
      # If you're using an external database or Render's database service:
      - key: DATABASE_URL
        sync: false  # Set this manually in the Render dashboard
      
      # Superuser creation (optional)
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      
      # AI configuration (using local fallback for free tier)
      - key: OLLAMA_BASE_URL
        value: "http://localhost:11434"  # Default to local Ollama instance
      - key: OLLAMA_MODEL
        value: "mistral"
      - key: WHISPER_ENABLED
        value: "False"
      
      # Optional Twilio configuration
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_FROM
        sync: false

# Note: For free tier deployment, we're not including the AI service or database definitions
# If you need a database, create it manually in the Render dashboard and set DATABASE_URL
